<a href="https://colab.research.google.com/github/Shubham-Jana-Dev/Data-Science/blob/main/Pandas/01_Pandas_Key_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
Data = {
    "Names":["Shubham","Rahul","Bikash","Dipak","Suman","Rudra","Milan","Sujoy"],
    "Marks":[98,98,78,67,66,90,89,92],
    "Adress":["Kolkata","Medinipur","Bakura","Birbhum","Malda","Jharagram","KuchBihar","Alipur"]
}

In [ ]:
df = pd.DataFrame(Data)
display(df)

     Names  Marks     Adress
0  Shubham     98    Kolkata
1    Rahul     98  Medinipur
2   Bikash     78     Bakura
3    Dipak     67    Birbhum
4    Suman     66      Malda
5    Rudra     90  Jharagram
6    Milan     89  KuchBihar
7    Sujoy     92     Alipur

In [ ]:
df.head(2)

     Names  Marks     Adress
0  Shubham     98    Kolkata
1    Rahul     98  Medinipur

In [ ]:
df.tail(3)

   Names  Marks     Adress
5  Rudra     90  Jharagram
6  Milan     89  KuchBihar
7  Sujoy     92     Alipur

In [ ]:
length = df["Marks"].count()
print(length)

8

In [ ]:
display(df["Marks"].count())

np.int64(8)

In [ ]:
marks = np.array(df["Marks"])
display(marks)

array([98, 98, 78, 67, 66, 90, 89, 92])

In [ ]:
display(marks*2)

array([196, 196, 156, 134, 132, 180, 178, 184])

In [ ]:
display(np.average(marks))

np.float64(84.75)

In [ ]:
display(np.mean(marks))

np.float64(84.75)

In [ ]:
display(np.median(marks))

np.float64(89.5)

In [ ]:
display(np.std(marks))

np.float64(12.04937757728589)

In [ ]:
display(np.mod(marks,67))

array([31, 31, 11,  0, 66, 23, 22, 25])

In [ ]:
# Just practice numpy a little bit 🤏 :)

In [ ]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   8 non-null      object
 1   Marks   8 non-null      int64
 2   Adress  8 non-null      object
dtypes: int64(1), object(2)
memory usage: 324.0+ bytes

None